import { Role } from "@/types/roles";

export const ROLES: Role[] = [
  {
    id: "senior-frontend-engineer",
    title: "Senior Frontend Engineer",
    company: "Nimbus Inc.",
    difficulty: "advanced",
    duration: "45 min",
    rating: 4.9,
    tags: ["React", "System Design", "Performance"],
  },
  {
    id: "product-manager",
    title: "Product Manager",
    company: "Vertex Labs",
    difficulty: "intermediate",
    duration: "30 min",
    rating: 4.7,
    tags: ["Strategy", "Prioritization"],
  },
  {
    id: "backend-engineer",
    title: "Backend Engineer",
    company: "Orbital",
    difficulty: "advanced",
    duration: "50 min",
    rating: 4.8,
    tags: ["APIs", "Databases", "Scalability"],
  },
  {
    id: "ux-researcher",
    title: "UX Researcher",
    company: "Fenwick",
    difficulty: "beginner",
    duration: "25 min",
    rating: 4.5,
    tags: ["User Interviews", "Synthesis"],
  },
  {
    id: "data-scientist",
    title: "Data Scientist",
    company: "Quanta",
    difficulty: "intermediate",
    duration: "40 min",
    rating: 4.6,
    tags: ["Statistics", "ML", "SQL"],
  },
  {
    id: "engineering-manager",
    title: "Engineering Manager",
    company: "Halcyon",
    difficulty: "advanced",
    duration: "45 min",
    rating: 4.9,
    tags: ["Leadership", "Conflict Resolution"],
  },
  {
    id: "marketing-lead",
    title: "Marketing Lead",
    company: "Rivet",
    difficulty: "intermediate",
    duration: "30 min",
    rating: 4.4,
    tags: ["Growth", "Brand Strategy"],
  },
  {
    id: "junior-swe",
    title: "Junior Software Engineer",
    company: "Northstar",
    difficulty: "beginner",
    duration: "35 min",
    rating: 4.6,
    tags: ["DSA", "Fundamentals"],
  },
];
